AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  antony-go

  Sample SAM Template for antony-go

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE

  ParrotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: parrot/
      Handler: parrot
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            Path: /parrot
            Method: GET
      Environment:
        Variables:
          DEFAULT_NAME: Default Name
